# Generated by Django 4.1 on 2022-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0002_alter_stories_options_rename_text_stories_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='source',
            field=models.CharField(default='The Economist', max_length=100),
        ),
    ]
